//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FH.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Inventory.
        /// </summary>
        public static string ADD_TO_INVENTORY {
            get {
                return ResourceManager.GetString("ADD_TO_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! Error Occured. Please Try Again..
        /// </summary>
        public static string ADD_TO_INVENTORY_EXCEPTION {
            get {
                return ResourceManager.GetString("ADD_TO_INVENTORY_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Invoice.
        /// </summary>
        public static string ADD_TO_INVOICE {
            get {
                return ResourceManager.GetString("ADD_TO_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop No - 11,&amp;#10;Sumeru Arc, Behind Bus Stop,&amp;#10;Near Divdi,Rupani Circle,&amp;#10;Bhavnagar - 364001.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BRAND_NAME {
            get {
                return ResourceManager.GetString("BRAND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not print at this time. Try sometime later..
        /// </summary>
        public static string CANNOTPRINT {
            get {
                return ResourceManager.GetString("CANNOTPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date .
        /// </summary>
        public static string CURRENTDATE {
            get {
                return ResourceManager.GetString("CURRENTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Rate.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount @ {0} %.
        /// </summary>
        public static string DISCOUNT_RATE {
            get {
                return ResourceManager.GetString("DISCOUNT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}.
        /// </summary>
        public static string DISCOUNTED_AMOUNT {
            get {
                return ResourceManager.GetString("DISCOUNTED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide customer name..
        /// </summary>
        public static string EMPTY_CUSTOMERNAME {
            get {
                return ResourceManager.GetString("EMPTY_CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Name..
        /// </summary>
        public static string EMPTY_USERNAME {
            get {
                return ResourceManager.GetString("EMPTY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date can not be greater than To Date..
        /// </summary>
        public static string FROMISGREATERTHANTO {
            get {
                return ResourceManager.GetString("FROMISGREATERTHANTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Brand Name..
        /// </summary>
        public static string INVALID_BRANDNAME {
            get {
                return ResourceManager.GetString("INVALID_BRANDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorrect..
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Piece number..
        /// </summary>
        public static string INVALID_PIECES {
            get {
                return ResourceManager.GetString("INVALID_PIECES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Price Value..
        /// </summary>
        public static string INVALID_PRICE {
            get {
                return ResourceManager.GetString("INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some item from Invoice..
        /// </summary>
        public static string INVALID_SELECTION {
            get {
                return ResourceManager.GetString("INVALID_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to really sell at this price?.
        /// </summary>
        public static string INVALID_SELLING_PRICE {
            get {
                return ResourceManager.GetString("INVALID_SELLING_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Style Code..
        /// </summary>
        public static string INVALID_STYLECODE {
            get {
                return ResourceManager.GetString("INVALID_STYLECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Item Type..
        /// </summary>
        public static string INVALID_TYPE {
            get {
                return ResourceManager.GetString("INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Report.
        /// </summary>
        public static string INVENTORY_REPORT {
            get {
                return ResourceManager.GetString("INVENTORY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        public static string INVOICEID {
            get {
                return ResourceManager.GetString("INVOICEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FH33{0:00000}.
        /// </summary>
        public static string INVOICEID_FORMAT {
            get {
                return ResourceManager.GetString("INVOICEID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Some Brand..
        /// </summary>
        public static string NO_ITEM_SELECTED {
            get {
                return ResourceManager.GetString("NO_ITEM_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Pieces.
        /// </summary>
        public static string NO_OF_PIECES {
            get {
                return ResourceManager.GetString("NO_OF_PIECES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Some Style Code..
        /// </summary>
        public static string NO_STYLECODE_SELECTED {
            get {
                return ResourceManager.GetString("NO_STYLECODE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        public static string PERCENTAGE_FORMAT {
            get {
                return ResourceManager.GetString("PERCENTAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough pieces in stock..
        /// </summary>
        public static string PIECES_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("PIECES_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.P.P.
        /// </summary>
        public static string PRICE_PER_PIECE {
            get {
                return ResourceManager.GetString("PRICE_PER_PIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string PURCHASE_PRICE {
            get {
                return ResourceManager.GetString("PURCHASE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        public static string SALES_REPORT {
            get {
                return ResourceManager.GetString("SALES_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        public static string SELLING_PRICE {
            get {
                return ResourceManager.GetString("SELLING_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign:.
        /// </summary>
        public static string SIGNATURE {
            get {
                return ResourceManager.GetString("SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Code.
        /// </summary>
        public static string STYLE_CODE {
            get {
                return ResourceManager.GetString("STYLE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL:.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
    }
}
