USE [master]
GO

/****** Object:  Database [InventoryDB]    Script Date: 07/23/2014 22:36:37 ******/
CREATE DATABASE [InventoryDB] ON  PRIMARY 
( NAME = N'InventoryDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\InventoryDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InventoryDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\InventoryDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [InventoryDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoryDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoryDB] SET  READ_WRITE 
GO

ALTER DATABASE [InventoryDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InventoryDB] SET  MULTI_USER 
GO

ALTER DATABASE [InventoryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoryDB] SET DB_CHAINING OFF 
GO

